# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/games" = {
    device = "/dev/disk/by-uuid/d9a88f45-ab4a-4f43-95de-524d8acea478";
    fsType = "btrfs";
    options = [ "subvol=@games" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1064-0A0A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/var/swapfile"; } ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
